image:
  repository: webbeds.azurecr.io/uhi
  tag: 1.0.6-dev
  pullPolicy: IfNotPresent
replicaCount: 1
imagePullSecrets:
  - name: registrykey
service:
  type: LoadBalancer
  port: 80
ingress:
  host: uhi-stage.webbeds.com
appPort: 3000
