module.exports = Object.freeze({
	LOGO: '/static/btob/images/LogoUHI.svg',
	PAGE_NAME_HOME: 'UHI Travel',
	RATINGS : {559: 1, 560: 2,561: 3,562: 4,563: 5},
	SELECTBUTTONTEXT : 'Select',
	FROMTEXT : 'from',
	KAABA_LATITUDE : '21.4225',
	KAABA_LONGTITUDE : '39.8262',
	MAKKAH:164,
	MADINAH:174,
	CURRENCY:492,
	SALUTATION:147,
	STEP_DEFAULT: 5,
	STEP_TEXT_MAKKAH : 'Makkah Hotel',
	STEP_TEXT_MADINAH : 'Madinah Hotel',
	STEP_TEXT_TRANSPORTATION : 'Transportation',
	STEP_TEXT_GROUNDSERVICES : 'Ground Services',
	STEP_TEXT_VISA : 'VISA',
	STEP_CONFIRMATION : 'Confirmation',
	STEP_PASSENGER : 'Passengers',
	STEP_PAYMENT : 'Payment',
	STEP_BOOKING_DETAILS : 'Booking details',
	PERPAGE: 5,
	LANGUAGES_EN: 'en',
	LANGUAGES_EN_LABEL: 'English',
	LANGUAGES_EN_LABEL_SHORT: 'ENG',
	LANGUAGES_EN_ICON: '/static/btob/icons/ic_flag_en.svg',
	LANGUAGES_AR: 'ar',
	LANGUAGES_AR_LABEL: 'Arabic',
	LANGUAGES_AR_LABEL_SHORT: 'AR',
	LANGUAGES_AR_ICON: '/static/btob/icons/saudi_arabia.ksa.gif',

	MAKKAH_HOTEL_RESEARCH_URL: '/package/rebook/hotel/makkah/search',
	MADINAH_HOTEL_RESEARCH_URL: '/package/rebook/hotel/madinah/search',
	TRANSFER_HOTEL_RESEARCH_URL: '/package/rebook/transfer/search',
	GROUND_SERVICE_HOTEL_RESEARCH_URL: '/package/rebook/groundservice/search',

	MAKKAH_HOTEL_SEARCH_URL: '/package/hotels/makkah/results',
	MADINAH_HOTEL_SEARCH_URL: '/package/hotels/madinah/results',
	BTOB_MAKKAH_HOTEL_SEARCH_URL: '/umrah-package/hotels/makkah/results',
	BTOB_MADINAH_HOTEL_SEARCH_URL: '/umrah-package/hotels/madinah/results',
	TRANSFER_SEARCH_URL: '/package/transfer',
	BTOC_TRANSFER_SEARCH_URL: '/umrah-package/transfer',
	GROUND_SERVICE_SEARCH_URL: '/package/groundservice',
	PACKAGE_CONFIRMATION_URL: '/package/confirmation/register',
	PACKAGE_LOGIN_URL: '/package/confirmation/login',
	PACKAGE_VERIFICATION_URL: '/package/confirmation/verification',
	USER_PASSENGER_URL: '/users/passengers',
	USER_PAYMENT_URL: '/users/payment',
	USER_BOOKING_CONFIRMATION: '/users/booking-confirmation',
	USER_BOOKING_DETAILS: '/users/booking-details',
	USER_MY_BOOKING: '/users/my-booking',

	PAYDOCK_WIDGET_KEY:'15e9514ff5d1f5a04dee86ae7da700903a9eb095',
	CUSTOMER_TYPE_CREDIT: '551',
	CUSTOMER_TYPE_CC: '552',

	VISA_STATUS_SAVED: 'SAVED',
	VISA_STATUS_ON_REQUEST: 'PENDING',
	VISA_STATUS_CONFIRM: 'CONFIRMED',
	VISA_STATUS_CANCEL: 'CANCELLED',
	VISA_STATUS_INCOMPLETE: 'INCOMPLETE',
	UO_STATUS_APPROVED: 'APPROVED',
	UO_STATUS_REJECTED: 'REJECTED',
	UO_STATUS_INCOMPLETE: 'INCOMPLETE',
	PASSPORT_NUMBER_VISA: 'P123456',
	REQUESTFROM: 'myBooking',
	HOTEL_SERVICE_ID: 1,
	TRANSFER_SERVICE_ID: 3,
	GROUND_SERVICE_ID: 4,
	VISA_SERVICE_ID: 5,
	MAQAM_BOOKING_SAVED: 'SAVED',
	MAQAM_BOOKING_CANCELLED: 'CANCELLED',
	MAQAM_BOOKING_CONFIRMED: 'CONFIRMED',
	MAQAM_BOOKING_INCOMPLETE: 'INCOMPLETE',
	BLOG_POST_URL: 'https://www.gatewaytosaudi.com/post/',
	AUTH_TOKEN_EXPIRY: 86400000,
	REQUEST_DEMO_ENDPOINT: 'https://prod-03.australiasoutheast.logic.azure.com:443/workflows/4ef4443af7f54b3f8bf4c2e4a87b4dee/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=gdJns2UN_OCvYdsdBQM4OzYZwRdv_aFEvLdnA2CS7-I',
	CUSTOMER_PAYMENT_TYPE_CREDIT_CARD:552,
	CUSTOMER_PAYMENT_TYPE_CREDIT:551,
	CUSTOMER_PAYMENT_TYPE_CASH:550,
	GROSS_COMMISSION_TYPE:1,
	GROSS_COMMISSION_VALUE:1,
	DIRECT_DEBIT:1,
	CURRENCY_CREDIT_CARD:520,
	CURRENCY_CREDIT_GROSS:0,
	FINANCE_DEPARTMENT_EMAIL_ADDRESS:'financeadmin@webbeds.com',
	VISA_SAFA_STATUS_SAVE: 'save',
	VISA_SAFA_STATUS_CONFIRM: 'confirm',
	VISA_SAFA_STATUS_BOTH: 'both',
	B2B_VISA_STATUS_INCOMPLETE: 0,
	B2B_VISA_STATUS_VALID: 1,
	B2B_VISA_STATUS_APPROVED: 2,
	B2B_VISA_STATUS_DENIED: 3,
	B2B_VISA_STATUS_PAID: 4,
	B2B_VISA_STATUS_REJECTED: 5,
	B2B_DEFAULT_CURRENCY: 'SAR',
	VISA_EXPIRE_ALERT_DAYS: 10,
	BFF_LOGIN_URL: ((process.env.NODE_ENV == 'development') ? process.env.REACT_APP_API_BASE_DEV : process.env.REACT_APP_API_BASE) + 'login',
	BFF_LOGOUT_URL: ((process.env.NODE_ENV == 'development') ? process.env.REACT_APP_API_BASE_DEV : process.env.REACT_APP_API_BASE) + 'logout',
	BFF_OIDC_ERROR: 'oidc_error=true',
	BFF_OIDC_ERROR_TEXT: 'An error occurred. Please try to log in again.',
	DOTW_BACKEND_STAGE_URL: 'http://umrah-accommodation.stage.aws.dotw.com/interface/en/',
	CREDIT_CARD_IFRAME_URL_DEV: 'https://securepay.dev.rezpayments.com/webbeds/paymentcard.html?callFrom=UMRAHNEW',
	CREDIT_CARD_TARGET_URL_DEV: 'https://securepay.dev.rezpayments.com/webjet/paymentcard.html',
	CREDIT_CARD_TOKENIZE_URL_DEV: 'https://securepayapi.dev.rezpayments.com/',
	CREDIT_CARD_RETURN_URL_DEV: 'https://localhost/',
	CREDIT_CARD_IFRAME_URL_PROD: 'https://securepay.rezpayments.com/webbeds/paymentcard.html?callFrom=UMRAHNEW',
	CREDIT_CARD_TARGET_URL_PROD :'https://securepay.rezpayments.com/webjet/paymentcard.html',
	CREDIT_CARD_TOKENIZE_URL_PROD :'https://securepayapi.rezpayments.com/',
	CREDIT_CARD_RETURN_URL_PROD: 'https://localhost/',
});